Fix build with GCC 16 on musl by adding missing <cstdint>
Add missing <cstdint> include in src/gn/pool.h for int64_t.
musl does not transitively include <cstdint>, causing build
failures when building with GCC 16 on musl:

  src/gn/pool.h:26:3: error: 'int64_t' does not name a type

Change-Id: Ie7a3d75f86e0cf16bb53355373de71d29fc2be85
Reviewed-on: https://gn-review.googlesource.com/c/gn/+/22740
Commit-Queue: Takuto Ikuta <tikuta@google.com>
Reviewed-by: Takuto Ikuta <tikuta@google.com>
Reviewed-by: Khem Raj <raj.khem@gmail.com>
Reviewed-by: David Turner <digit@google.com>